# Generated by Django 5.2.8 on 2025-11-13 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagens', '0002_loja_limite_carros_loja_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='loja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loja',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garagens.cidade'),
        ),
    ]
