# Generated by Django 5.2.8 on 2025-11-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagens', '0003_cidade_alter_loja_usuario_loja_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lojas', to='garagens.cidade'),
        ),
    ]
