# Generated by Django 5.2.8 on 2025-11-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagens', '0004_alter_loja_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
