# Generated by Django 5.2.8 on 2025-11-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='carros/')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='garagens.loja')),
            ],
        ),
    ]
