# Generated by Django 5.2.8 on 2025-11-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='carros/fotos/')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='carros.carro')),
            ],
        ),
    ]
