# Generated by Django 5.2.8 on 2025-11-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_marca_alter_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
