# Generated by Django 5.2.8 on 2025-11-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
