# Generated by Django 5.2.8 on 2025-11-15 06:08

import carros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_delete_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='carros/', validators=[carros.models.validar_proporcao_imagem]),
        ),
        migrations.AlterField(
            model_name='fotocarro',
            name='imagem',
            field=models.ImageField(upload_to='carros/fotos/', validators=[carros.models.validar_proporcao_imagem]),
        ),
    ]
