# Generated by Django 5.2.8 on 2025-11-26 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0012_categoriaveiculo_imagem_alter_carro_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes_carro', to='carros.carro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_visualizacao'],
                'indexes': [models.Index(fields=['usuario', '-data_visualizacao'], name='carros_visu_usuario_6cf6c6_idx')],
            },
        ),
    ]
